// <auto-generated />
using System;
using Magpie.Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Magpie.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200816104344_Addtrade")]
    partial class Addtrade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Magpie.Framework.Json.StockMarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TradeCodeId")
                        .HasColumnType("int");

                    b.Property<float>("close")
                        .HasColumnType("real");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<float>("high")
                        .HasColumnType("real");

                    b.Property<float>("low")
                        .HasColumnType("real");

                    b.Property<float>("open")
                        .HasColumnType("real");

                    b.Property<decimal>("volumn")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TradeCodeId");

                    b.ToTable("StockMarkets");
                });

            modelBuilder.Entity("Magpie.Framework.Trade.TradeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("trade_code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradeCodes");
                });

            modelBuilder.Entity("Magpie.Framework.Json.StockMarket", b =>
                {
                    b.HasOne("Magpie.Framework.Trade.TradeCode", "TradeCode")
                        .WithMany("StockMarkets")
                        .HasForeignKey("TradeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
